language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm
  - nightly
  - 7.0

before_install:
  composer self-update

install:
  composer install --no-interaction

script:
  php ./vendor/bin/phing static-analysis test

after_success:
  php ./vendor/bin/coveralls -v
